### ISSUE TITLE
Add Github Workflows

### ISSUE THREAD

**Issue by justlevine** [harness-software/wp-graphql-gravity-forms#117]
PR's should be pass phpcs, phpstan, and codeception in order to be approved.

Possibly helpful references: 
- https://github.com/sdras/awesome-actions
- https://github.com/wp-graphql/wp-graphql/tree/develop/.github/workflows

# Workflows to implement:
- [x] PHPCS 
- [x] PHPStan
- [x] Unit Tests ~~(Blocked by #150)~~
- [x] GraphQL Schema diffs.
- [x] Codeclimate

**Comment by justlevine** [comment]
#230 added PHPStan tests. They don't run on PRs to develop, since Github Secrets don't work on forks, but they will run once the merge is approved.

WPUnit tests are [currently stuck](https://github.com/justlevine/wp-graphql-gravity-forms/runs/5487941458?check_suite_focus=true) due to a Fatal Error:
```log
PHP Fatal error:  Uncaught TypeError: ftp_pwd(): Argument #1 ($ftp) must be of type resource, null given in /var/www/html/wp-admin/includes/class-wp-filesystem-ftpext.php:230
Stack trace:
#0 /var/www/html/wp-admin/includes/class-wp-filesystem-ftpext.php(230): ftp_pwd(NULL)
#1 /var/www/html/wp-admin/includes/class-wp-filesystem-ftpext.php(450): WP_Filesystem_FTPext->cwd()
#2 /var/www/html/wp-content/plugins/gravityforms/includes/class-translationspress-updater.php(316): WP_Filesystem_FTPext->is_dir('/var/www/html/w...')
#3 /var/www/html/wp-content/plugins/gravityforms/includes/class-translationspress-updater.php(287): Gravity_Forms\Gravity_Forms\TranslationsPress_Updater->install_translation(Array)
#4 /var/www/html/wp-includes/class-wp-hook.php(305): Gravity_Forms\Gravity_Forms\TranslationsPress_Updater->install()
#5 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#6 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#7 /var/www/html/wp-content/plugins/gravityforms/includes/class-gf-upgrade.php(202): do_action('gform_post_inst...', '2.5.14')
#8 /var/www/html/wp-content/plugins/gravityforms/includes/class-gf-upgrade.php(73): GF_Upgrade->install()
#9 /var/www/html/wp-content/plugins/gravityforms/gravityforms.php(740): GF_Upgrade->maybe_upgrade()
#10 /var/www/html/wp-includes/class-wp-hook.php(307): GFForms::activation_hook(false)
#11 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#12 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#13 /var/www/html/wp-admin/includes/plugin.php(689): do_action('activate_gravit...', false)
#14 /var/www/html/wp-content/plugins/wp-graphql-gravity-forms/vendor/lucatume/wp-browser/src/includes/isolated-install.php(204): activate_plugin('gravityforms/gr...', NULL, false, false)
#15 {main}
  thrown in /var/www/html/wp-admin/includes/class-wp-filesystem-ftpext.php on line 230

In bootstrap.php line 150:
                                                                               
  thrown in /var/www/html/wp-admin/includes/class-wp-filesystem-ftpext.php on  
   line 230  
```

**Comment by justlevine** [comment]
Need app access to CodeClimate to complete this.

cc: @tinytoolbox
