### ISSUE TITLE
[Bug] PHP Fatal error: Uncaught Error: Failed opening required .../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php

### ISSUE THREAD

**Issue by ttstauss** [harness-software/wp-graphql-gravity-forms#240]
## Describe the bug

Installed and activated WPGraphQL.
Installed and activated Gravity Forms.
Downloaded the repo zip and uploaded to WordPress and activated.
Get the following WordPress error (There has been a critical error on this website. Please check your site admin email inbox for instructions.):

```
PHP Fatal error:  Uncaught Error: Failed opening required '/nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/../yahnis-elsts/plugin-update-checker/load-v4p11.php' (include_path='.:/usr/share/pear/php:/usr/share/php') in /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php:78\nStack trace:\n#0 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php(61): composerRequire0e8f6c0730ce438688b3484326e9667b('49a1299791c25c6...', '/nas/content/li...')\n#1 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/autoload.php(7): ComposerAutoloaderInit0e8f6c0730ce438688b3484326e9667b::getLoader()\n#2 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/src/GF.php(55): require_once('/nas/content/li...')\n#3 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/src/GF.php(34): WPGraphQL\\GF\\GF->includes()\n#4 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/wp-graphql-gravity-forms.php(90): WPGraphQL\\GF\\GF::instance()\n#5 /nas/content/live/../wp-includes/class-wp-hook.php(307): gf_graphql_init(Object(WPGraphQL))\n#6 /nas/content/live/../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)\n#7 /nas/content/live/../wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#8 /nas/content/live/../wp-content/plugins/wp-graphql/src/WPGraphQL.php(255): do_action('graphql_init', Object(WPGraphQL))\n#9 /nas/content/live/../wp-includes/class-wp-hook.php(307): WPGraphQL->{closure}('')\n#10 /nas/content/live/../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#11 /nas/content/live/../wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#12 /nas/content/live/../wp-settings.php(565): do_action('after_setup_the...')\n#13 /nas/content/live/../wp-config.php(119): require_once('/nas/content/li...')\n#14 /nas/content/live/../wp-load.php(50): require_once('/nas/content/li...')\n#15 /nas/content/live/../wp-admin/admin.php(34): require_once('/nas/content/li...')\n#16 /nas/content/live/../wp-admin/plugins.php(10): require_once('/nas/content/li...')\n#17 {main}\n  thrown in /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php on line 78, referer: https://...wpengine.com/wp-admin/update.php?action=upload-plugin
PHP Fatal error:  Uncaught Error: Failed opening required '/nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/../yahnis-elsts/plugin-update-checker/load-v4p11.php' (include_path='.:/usr/share/pear/php:/usr/share/php') in /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php:78\nStack trace:\n#0 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php(61): composerRequire0e8f6c0730ce438688b3484326e9667b('49a1299791c25c6...', '/nas/content/li...')\n#1 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/autoload.php(7): ComposerAutoloaderInit0e8f6c0730ce438688b3484326e9667b::getLoader()\n#2 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/src/GF.php(55): require_once('/nas/content/li...')\n#3 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/src/GF.php(34): WPGraphQL\\GF\\GF->includes()\n#4 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/wp-graphql-gravity-forms.php(90): WPGraphQL\\GF\\GF::instance()\n#5 /nas/content/live/../wp-includes/class-wp-hook.php(307): gf_graphql_init(Object(WPGraphQL))\n#6 /nas/content/live/../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)\n#7 /nas/content/live/../wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#8 /nas/content/live/../wp-content/plugins/wp-graphql/src/WPGraphQL.php(255): do_action('graphql_init', Object(WPGraphQL))\n#9 /nas/content/live/../wp-includes/class-wp-hook.php(307): WPGraphQL->{closure}('')\n#10 /nas/content/live/../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#11 /nas/content/live/../wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#12 /nas/content/live/../wp-settings.php(565): do_action('after_setup_the...')\n#13 /nas/content/live/../wp-config.php(119): require_once('/nas/content/li...')\n#14 /nas/content/live/../wp-load.php(50): require_once('/nas/content/li...')\n#15 /nas/content/live/../wp-admin/admin.php(34): require_once('/nas/content/li...')\n#16 /nas/content/live/../wp-admin/update.php(16): require_once('/nas/content/li...')\n#17 {main}\n  thrown in /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php on line 78, referer: https://...wpengine.com/wp-admin/plugin-install.php?s=wpgraphql&tab=search&type=term
PHP Fatal error:  Uncaught Error: Failed opening required '/nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/../yahnis-elsts/plugin-update-checker/load-v4p11.php' (include_path='.:/usr/share/pear/php:/usr/share/php') in /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php:78\nStack trace:\n#0 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php(61): composerRequire0e8f6c0730ce438688b3484326e9667b('49a1299791c25c6...', '/nas/content/li...')\n#1 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/autoload.php(7): ComposerAutoloaderInit0e8f6c0730ce438688b3484326e9667b::getLoader()\n#2 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/src/GF.php(55): require_once('/nas/content/li...')\n#3 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/src/GF.php(34): WPGraphQL\\GF\\GF->includes()\n#4 /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/wp-graphql-gravity-forms.php(90): WPGraphQL\\GF\\GF::instance()\n#5 /nas/content/live/../wp-includes/class-wp-hook.php(307): gf_graphql_init(Object(WPGraphQL))\n#6 /nas/content/live/../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)\n#7 /nas/content/live/../wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#8 /nas/content/live/../wp-content/plugins/wp-graphql/src/WPGraphQL.php(255): do_action('graphql_init', Object(WPGraphQL))\n#9 /nas/content/live/../wp-includes/class-wp-hook.php(307): WPGraphQL->{closure}('')\n#10 /nas/content/live/../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#11 /nas/content/live/../wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#12 /nas/content/live/../wp-settings.php(565): do_action('after_setup_the...')\n#13 /nas/content/live/../wp-config.php(119): require_once('/nas/content/li...')\n#14 /nas/content/live/../wp-load.php(50): require_once('/nas/content/li...')\n#15 /nas/content/live/../wp-admin/admin.php(34): require_once('/nas/content/li...')\n#16 /nas/content/live/../wp-admin/plugin-install.php(16): require_once('/nas/content/li...')\n#17 {main}\n  thrown in /nas/content/live/../wp-content/plugins/wp-graphql-gravity-forms-develop/vendor/composer/autoload_real.php on line 78, referer: https://...wpengine.com/wp-admin/plugins.php
```

## To Reproduce

1. Install & activate WPGraphQL.
2. Install & activate Gravity Forms and any supported addons.
3. Download the zip of this repository and upload it to your WordPress install, and activate the plugin.

## Expected behavior

Plugin to not crash WordPress.

## Additional context

Hosted on WPEngine.

### Technical Info
* WordPress version: 5.9.2
* WPGraphQL version: 1.7.2
* Gravity Forms version: 2.5.16
* WPGraphQL for Gravity Forms version: v0.10.5
* Other relevant frameworks/plugins:

<html>
<body>

Plugin Name | Plugin Version
-- | --
Advanced Custom Fields PRO | by Delicious Brains - 5.12
Atlas Content Modeler | by WP Engine - 0.14.0
Code Snippets | by Code Snippets Pro - 2.14.3
FaustWP | by WP Engine - 0.7.6
Genesis Custom Blocks | by Genesis Custom Blocks - 1.4.0
WordPress Importer | by wordpressdotorg - 0.7
WP GraphQL | by WPGraphQL - 1.7.2
WPGraphQL for Advanced Custom Fields | by WPGraphQL, Jason Bahl - 0.5.3
WP GraphQL Gutenberg | by pristas-peter - 0.3.11

</body>
</html>

**Comment by justlevine** [comment]
Hey @ttstauss 

Seems you downloaded the `develop` branch. If that was intentional, you can run `composer install` to grab the missing dependencies.

Seems I neglected to update the .gitignore after the update checker commit.

**Comment by ttstauss** [comment]
Ah, yeah, I wondered if that would be the case. Thanks!
